### ISSUE TITLE
选择一个方向

### ISSUE THREAD

**Issue by AttackPangHu** [SHUAXINDIARY/shuaxindiary.github.io#1]
先选择好一个方向，前端可以继续Vue.js
后端的话建议就不要Node.js 可以选择Java Go Php这些能应对企业级的开放语言
长远来看，建议选择后端

**Comment by SHUAXINDIARY** [comment]
谢谢老哥的建议，个人是比较喜欢前端，所以想先扎实好前端相关技术基础；然后以前端为点，慢慢画圆这样展开对web技术都进行一些涉猎的学习
