### ISSUE TITLE
textarea标签tab键无效 | 刷新

### ISSUE THREAD

**Issue by SHUAXINDIARY** [SHUAXINDIARY/shuaxindiary.github.io#3]
https://blog.shuaxinjs.cn/2020/12/27/%E6%8A%80%E6%9C%AF%E7%AC%94%E8%AE%B0/textarea%E6%A0%87%E7%AD%BEtab%E9%94%AE%E6%97%A0%E6%95%88/ 

 最近在实现一个自己的浏览器版md编辑器，初步是使用textarea作为输入端，但是textarea里tab键，会失效，记录一下这个坑

**Comment by SHUAXINDIARY** [comment]
测试评论

**Comment by w1002767501** [comment]
滴滴...

**Comment by SHUAXINDIARY** [comment]
> 测试评论

测试回复

**Comment by SHUAXINDIARY** [comment]
> @w1002767501
> 滴滴...

测试回复
